// Dashboard
export const SET_DASHBOARD_LAYOUT = 'SET_DASHBOARD_LAYOUT'
export const ADD_WIDGET_TO_DASHBOARD = 'ADD_WIDGET_TO_DASHBOARD'
export const FETCH_DASHBOARD = 'FETCH_DASHBOARD'
export const UPDATE_DASHBOARD = 'UPDATE_DASHBOARD'
export const DESTROY_DASHBOARD = 'DESTROY_DASHBOARD'
export const SET_DASHBOARD_STATE = 'SET_DASHBOARD_STATE'

// Dashboards
export const SET_DASHBOARDS_ITEMS = 'SET_DASHBOARDS_ITEMS'
export const SET_TITLE_INPUT = 'SET_TITLE_INPUT'
export const DELETE_DASHBOARD = 'DELETE_DASHBOARD'
export const SET_CURRENTLY_SELECTED_DASHBOARD =
  'SET_CURRENTLY_SELECTED_DASHBOARD'
export const SET_EDITING_DASHBOARD_TITLE = 'SET_EDITING_DASHBOARD_TITLE'
export const EDIT_DASHBOARD_TITLE = 'EDIT_DASHBOARD_TITLE'
export const FETCH_DASHBOARDS = 'FETCH_DASHBOARDS'
export const CREATE_DASHBOARD = 'CREATE_DASHBOARD'

// Widget
export const CREATE_WIDGET = 'CREATE_WIDGET'
export const UPDATE_WIDGETS = 'UPDATE_WIDGETS'
export const DESTROY_WIDGET = 'DESTROY_WIDGET'
export const SET_WIDGETS = 'SET_WIDGETS'
export const ADD_WIDGET = 'ADD_WIDGET'
export const SET_DRILLDOWN_INDEX = 'SET_DRILLDOWN_INDEX'
export const PUSH_HISTORY = 'PUSH_HISTORY'
export const SLICE_HISTORY = 'SLICE_HISTORY'
export const SET_CHART_TYPE = 'SET_CHART_TYPE'
export const SET_WIDGET_STATE = 'SET_WIDGET_STATE'

// Report
export const ADD_REPORT = 'ADD_REPORT'
export const FETCH_REPORT = 'FETCH_REPORT'
export const FETCH_WEEKLY_SPEND_REPORT = 'FETCH_WEEKLY_SPEND_REPORT'
export const SET_WEEKLY_SPEND_REPORT = 'SET_WEEKLY_SPEND_REPORT'
export const FETCH_GL_SPEND_REPORT = 'FETCH_GL_SPEND_REPORT'
export const SET_GL_SPEND_REPORT = 'SET_GL_SPEND_REPORT'
export const FETCH_VENDOR_SPEND_REPORT = 'FETCH_VENDOR_SPEND_REPORT'
export const SET_VENDOR_SPEND_REPORT = 'SET_VENDOR_SPEND_REPORT'
export const SET_REPORT_ATTRIBUTE = 'SET_REPORT_ATTRIBUTE'
export const SET_GLOBAL_REPORT_ATTRIBUTE = 'SET_GLOBAL_REPORT_ATTRIBUTE'
export const SET_REPORT_JOB_ID = 'SET_REPORT_JOB_ID'
export const SET_REPORT_ERROR = 'SET_REPORT_ERROR'

// Company
export const FETCH_LOCATIONS = 'GET_LOCATIONS'
export const SET_LOCATIONS = 'SET_LOCATIONS'
export const SET_LOCATIONS_BY_REGION = 'SET_LOCATIONS_BY_REGION'
export const AUTHORIZE = 'AUTHORIZE'
export const SET_COMPANY_DATA = 'SET_COMPANY_DATA'
export const FETCH_DATES = 'FETCH_DATES'

// General
export const GLOBAL_OVERWRITE = 'GLOBAL_OVERWRITE'

// COGS
export const FETCH_TREND_UNIT_GROUP_BY_GL = 'FETCH_TREND_UNIT_GROUP_BY_GL'
export const FETCH_TREND_UNIT_GROUP_BY_GL_SUCCESS =
  'FETCH_TREND_UNIT_GROUP_BY_GL_SUCCESS'
export const SET_GL_FILTERS = 'SET_GL_FILTERS'
export const UPDATE_GL_FILTERS = 'UPDATE_GL_FILTERS'
export const FETCH_ITEM_GL = 'FETCH_ITEM_GL'
export const FETCH_ITEM_GL_SUCCESS = 'FETCH_ITEM_GL_SUCCESS'
export const SWITCH_TO_SINGLE_GL = 'SWITCH_TO_SINGLE_GL'
export const SWITCH_CHART_TYPE = 'SWITCH_CHART_TYPE'
export const FETCH_ITEM_INV_LOC = 'FETCH_ITEM_INV_LOC'
export const FETCH_ITEM_INV_LOC_SUCCESS = 'FETCH_ITEM_INV_LOC_SUCCESS'
export const FETCH_INVOICES_GL = 'FETCH_INVOICES_GL'
export const FETCH_INVOICES_GL_SUCCESS = 'FETCH_INVOICES_GL_SUCCESS'
export const SET_ITEMS_TID = 'SET_ITEMS_TID'
export const UPDATE_ITEM_TID = 'UPDATE_ITEM_TID'
export const SELECT_ALL_GL_FILTERS = 'SELECT_ALL_GL_FILTERS'
export const SELECT_ALL_ITEMS = 'SELECT_ALL_ITEMS'
export const FETCH_INVOICES_BY_ITEM = 'FETCH_INVOICES_BY_ITEM'
export const FETCH_INVOICES_BY_ITEM_SUCCESS = 'FETCH_INVOICES_BY_ITEM_SUCCESS'
export const SET_ITEMS_USAGE_DISPLAY = 'SET_ITEMS_USAGE_DISPLAY'

// AP Spend
export const SET_DEFAULT_TREND_BY = 'SET_DEFAULT_TREND_BY'

// BudgetVsActual
export const SET_TOTAL_BUDGET_AMOUNT = 'SET_TOTAL_BUDGET_AMOUNT'

// Four R
export const SET_SELECTED_RECIPES = 'SET_SELECTED_RECIPES'
export const UPDATE_SELECTED_RECIPES = 'UPDATE_SELECTED_RECIPES'

export const SET_BY_INVOICE_DATE = 'SET_BY_INVOICE_DATE'

export const SET_DATA_FETCHING = 'SET_DATA_FETCHING'
